name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

##############################################################

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  HOME: /tmp/home
  WORKSPACE: /tmp/workspace

jobs:
  lints:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint

  node_tests:
    name: "Node Tests (${{ matrix.slice.name }})"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        slice:
          - name: app permutations 1/2
            args: test/ember.nvp/permutations/app-1.test.ts
          - name: app permutations 2/2
            args: test/ember.nvp/permutations/app-2.test.ts
          - name: library permutations 1/2
            args: test/ember.nvp/permutations/library-1.test.ts
          - name: library permutations 2/2
            args: test/ember.nvp/permutations/library-2.test.ts
          - name: extension permutations 1/2
            args: test/ember.nvp/permutations/extension-1.test.ts
          - name: extension permutations 2/2
            args: test/ember.nvp/permutations/extension-2.test.ts
          - name: check-layer permutations
            args: test/ember.nvp/permutations/app-checks.test.ts test/ember.nvp/permutations/library-checks.test.ts test/ember.nvp/permutations/extension-checks.test.ts
          - name: everything else
            args: --exclude 'test/ember.nvp/permutations/**'

    steps:
      - uses: wyvox/action@v1
      - run: |
          git config --global user.name "ci"
          git config --global user.email "non@none.none"
          pnpm test:node ${{ matrix.slice.args }}
